### ISSUE TITLE
License observation

### ISSUE THREAD

**Issue by bduranc** [evollu/react-native-fcm#1117]
Greetings,

I observe the file(s) located at:

Examples/simple-fcm-client/ios/SimpleFcmClient/AppDelegate.h
Examples/simple-fcm-client/ios/SimpleFcmClient/main.m
Examples/simple-fcm-client/ios/SimpleFcmClientTests/SimpleFcmClientTests.m
Examples/simple-fcm-client/ios/SimpleFcmClient/AppDelegate.m

, all mention a "PATENTS" file.

However, I cannot find this "PATENTS" file anywhere in the repository. If someone can explain why this is, that would be very helpful.

Thank you.

Kind Regards,
Brian

**Comment by mjmasn** [comment]
@bduranc I'm not the author, but I think that was Facebook's standard header for code in the React / React Native projects when the licence was BSD + Patents clause. They have since relicensed as MIT, and so there is no longer a PATENTS file. 

Compare e.g. https://github.com/facebook/react-native/tree/master (MIT) with https://github.com/facebook/react-native/tree/0.54-stable (BSD + Patents)

Those particular files look like boilerplate and were probably just copy/pasted from the React Native project. e.g. https://github.com/facebook/react-native/blob/master/template/ios/HelloWorld/AppDelegate.h

**Comment by bduranc** [comment]
This is would make sense. Thank you.
