### ISSUE TITLE
ios 10 support

### ISSUE THREAD

**Issue by sibelius** [evollu/react-native-fcm#117]
> For devices running iOS 10 and above, implement UNUserNotificationCenterDelegate userNotificationCenter:willPresentNotification:withCompletionHandler: to handle notifications received when the client app is in the foreground. The message is a UNNotification object. Implement FIRMessagingDelegate applicationReceivedRemoteMessage: to handle all data messages that are sent to the client. The message is a FIRMessagingRemoteMessage object.

@evollu check this out: https://firebase.google.com/docs/cloud-messaging/ios/receive

this should be done on user land or by react-native-fcm?

do u think?

**Comment by darkbaby123** [comment]
I also met the same issue on iOS 10 and did several days investigation from APNs to FCM to react-native-fcm. I'll list what I found here and wish it can help guys like me.

## New notification center for iOS 10

Pure FCM integration is very simple. You just implement iOS native callbacks in `AppDelegate.m` to execute some FCM methods. Before iOS 10 you just need 2 callbacks:

- `application:didReceiveRemoteNotification` to handle remote (push) notification.
- `application:didReceiveLocalNotification` to handle local notification.

While iOS 10 adds a whole new notification center class `UNUserNotificationCenter` and many things rely on it. You need to implement at least such callbacks to work on iOS 10 (only):

- `userNotificationCenter:willPresentNotification:withCompletionHandler` to receive remote notification in **foreground**. If this method is not implemented, iOS will use `application:didReceiveRemoteNotification` instead. But the callback will not be triggered for background notifications.
- `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler` to receive remote notification in **background**. It's triggered when the user presses the notification in notification center.

Above are for displayed notification. For data message, FCM provides `FIRMessagingDelegate` and `applicationReceivedRemoteMessage` callback to handle pure data message (when just send data without notification). Those messages are not pushed by APNs and I guess FCM runs a background service to handle them. Note that **notifications with data are sent by APNs** so they're handled by above 2 callbacks.

This doesn't include local notification because my case doesn't use local notification. And it seems local notification is also different, see [Apple's documentation](https://developer.apple.com/reference/usernotifications/unusernotificationcenter?language=objc) for details if you're interested.


## The possibly workaround

I follow [FCM's quickstart](https://github.com/firebase/quickstart-ios/blob/master/messaging/FCM/AppDelegate.m) and find a possible workaround. Below is a example to use above callbacks to handle notifications and data (just print message).

```objective-c
#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
@import UserNotifications;
#endif

@import Firebase;
@import FirebaseInstanceID;
@import FirebaseMessaging;

// Implement UNUserNotificationCenterDelegate to receive display notification via APNS for devices
// running iOS 10 and above. Implement FIRMessagingDelegate to receive data message via FCM for
// devices running iOS 10 and above.
#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
@interface AppDelegate () <UNUserNotificationCenterDelegate, FIRMessagingDelegate>
@end
#endif

// Copied from Apple's header in case it is missing in some cases (e.g. pre-Xcode 8 builds).
#ifndef NSFoundationVersionNumber_iOS_9_x_Max
#define NSFoundationVersionNumber_iOS_9_x_Max 1299
#endif

// react-native-fcm
#import "Firebase.h"
#import "RNFIRMessaging.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  if (floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_9_x_Max) {
    // iOS 9 and below
    // ...
  } else {
    // iOS 10 and above
    #if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
    UNAuthorizationOptions authOptions =
      UNAuthorizationOptionAlert
      | UNAuthorizationOptionSound
      | UNAuthorizationOptionBadge;
    [[UNUserNotificationCenter currentNotificationCenter]
      requestAuthorizationWithOptions:authOptions
      completionHandler:^(BOOL granted, NSError * _Nullable error) {
        NSLog(@">>> completionHandler %@ %@", granted ? @"YES" : @"NO", error);
      }
    ];

    // For iOS 10 display notification (sent via APNS)
    [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
    // For iOS 10 data message (sent via FCM)
    [[FIRMessaging messaging] setRemoteMessageDelegate:self];
    #endif
  }

  [[UIApplication sharedApplication] registerForRemoteNotifications];

  [FIRApp configure];

  // Add observer for InstanceID token refresh callback.
  [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:)
                                               name:kFIRInstanceIDTokenRefreshNotification object:nil];
}

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
    willPresentNotification:(UNNotification *)notification
    withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {

  // Print message ID.
  NSDictionary *userInfo = notification.request.content.userInfo;
  NSLog(@">>> iOS 10 Message ID: %@", userInfo[@"gcm.message_id"]);

  // Pring full message.
  NSLog(@">>> iOS 10 %@", userInfo);
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
    didReceiveNotificationResponse:(UNNotificationResponse *)response
    withCompletionHandler:(void (^)())completionHandler {

  // Use [response notification] to get notification (UNNotification instance).
  // The rest is the same as above callback.
}

// Receive data message on iOS 10 devices.
- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
  // Print full message
  NSLog(@"%@", [remoteMessage appData]);
}
#endif

@end
```

So how does it cooperate with react-native-fcm? I found that react-native-fcm just use some iOS native callbacks to get the notification and feed to `FCMNotificationReceived` event. And that event is just trigger React Native bridge. If we can pass the correct data to this event, then all JS level things should work correctly.

There's a problem though. iOS 10 callbacks returns `UNNotification` instance while react-native-fcm needs `NSNotification`. I don't know how to do the transformation here. Maybe react-native-fcm needs to register a new event for iOS 10 notifications.

That's all I know. Wish it helps for both repo author and the users. I'm not an iOS developer, actually I'm a front-end developer. And I'll go to another city for a few days, otherwise I'm glad to help (submit a PR). As you can see iOS 10 needs lots of boilplate code and it's not user friendly add them to README, I wish the plugin can handle most of logic internally.

**Comment by evollu** [comment]
great, I don't have time for now. a pull is welcomed

**Comment by evollu** [comment]
@darkbaby123 can you try passing `[NSNotification userInfo]` into FCM listener so that it is a dictionary?

**Comment by darkbaby123** [comment]
@evollu yes I saw you only use the `userInfo` to get raw data. And `UNNotification` also has it internally. It's a working solution.

**Comment by evollu** [comment]
after done some search, I find old iOS9 code should still work for iOS10. new functions for iOS10 is just providing more feature

**Comment by evollu** [comment]
or could the permission request process got changed?

**Comment by evollu** [comment]
new version of iOS SDK Firebase iOS SDK (v3.6.0) was released on 15 and as cocoapod user, you get it automatically. :(

**Comment by evollu** [comment]
@sibelius ios 10 support added. check master branch and see if everything works fine.
My suspect is that permission registration fails in iOS 10. That is why I can still receive notification

**Comment by siemya** [comment]
@evollu @darkbaby123 i "get cannot find protocol declaration for 'UNUserNotificationCenterDelegate'" after i modified appDelegate.h

**Comment by sibelius** [comment]
@evollu @darkbaby123 this package could also be a good resource https://github.com/wix/react-native-notifications

it has support for interactive notifications, I'm not sure if u wanna add this funcionallity to

**Comment by evollu** [comment]
@sibelius the this repo will get super complex with these local notification feature support. Let me solve tons of issues we have now first

**Comment by evollu** [comment]
@siemya add 
`@import UserNotifications;` in the header file. Will fix readme

**Comment by evollu** [comment]
@sibelius @darkbaby123 LMK if the published package works for you

**Comment by luisfuertes** [comment]
@evollu i have compile fail on `RNFIRMessaging.m`: `Module 'UserNotifications' not found. And in AppDelegate.h fail too. How can i fix it? 

I try to add '@import UserNotifications;' on `AppDelegate.h` and in `RNFIRMessaging.h` but it doesnt fix.

Some idea?

**Comment by sibelius** [comment]
@luisfuertes u should update to xcode 8, and u should also use the latest version of Firebase SDK (native)

**Comment by darkbaby123** [comment]
@evollu It works for me, thanks!

**Comment by sibelius** [comment]
it is working fine on ios 10

great work @evollu 🎉 

only FCM.getInitialNotification() is not working on android

**Comment by luisfuertes** [comment]
On iOS 10 devices are you receiving token? I only receive on previous versions, 9 and before :s Some idea?
