### ISSUE TITLE
Linking error IOs 

### ISSUE THREAD

**Issue by willoughby** [evollu/react-native-fcm#134]
I installed the firebase messaging pod with no problems, after linking I got the following build error. I am unable to post my project publicly, but can email it to you if required.

[![Screen Shot 2016-09-29 at 20.17.20.png](https://s17.postimg.org/yipogpzjj/Screen_Shot_2016_09_29_at_20_17_20.png)](https://postimg.org/image/4qsm1jcq3/)

`
"dependencies": {
    "firebase": "^3.4.0",
    "moment": "^2.15.1",
    "react": "15.3.2",
    "react-native": "0.34.0",
    "react-native-fcm": "^2.2.0",
    "react-native-vector-icons": "^2.1.0",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0"
  }
`

`pod 'Firebase'
  pod 'Firebase/Messaging'`

**Comment by nertilzhuri** [comment]
If you have installed firebase before updating please run pod update o  your ios project. I had this problem after updating, and the reason of the error was because I did not update my Firebase files.
Also check the AppDelegate.h and AppDelegate.m if they have been configured as it is described in the documentation.

I hope it helps.

**Comment by willoughby** [comment]
This is a new project so there isn't anything to update, the auto complete knows about the fire base sdk.

**Comment by willoughby** [comment]
I've switched to manually installing the firebase sdk and my issues resolved. I have quite a few issues with cocoa pods not working well with RN, it's a shame as its so handy.
