### ISSUE TITLE
Unsubscribing from fcm

### ISSUE THREAD

**Issue by mmazzarolo** [evollu/react-native-fcm#186]
Hey guys! 
First of all thank you for this lib, it's working really well so far 👍 

I'd like to know if there's any way to unsubscribe/invalidate the token for stopping all kind of push notifications.  
I'm working on an application that subscribe an user to fcm once logged in, and should unsubscribe him on logout.  
Currently on logout I'm already calling `refreshUnsubscribe()` and `notificationUnsubscribe()`, but this works only for the foreground notifications... it still shows notifications when the app is in background/killed.  

Any hints? 
Thank you in advance 👍 

P.S.: If anyone here uses Parse-Server and is interested I recently created a branch of [`parse-server-push-adapter` working with fcm.](https://github.com/parse-server-modules/parse-server-push-adapter/pull/41)

**Comment by evollu** [comment]
No, I don't think any push notification will support that.
Your feature sounds more like a real time connection rather than push notifications. I would use a socket server and build local notifications on new messages. Better authentication etc. React Native has socket client built in so it should be easy.

**Comment by mmazzarolo** [comment]
Thanks @evollu, at the time I opened the issue I wasn't completely aware of how push notification worked, you're right 👍
