### ISSUE TITLE
iOS can't clear local notification

### ISSUE THREAD

**Issue by otoinsa** [evollu/react-native-fcm#275]
FCM.removeDeliveredNotification("UNIQ_ID_STRING")
is not working on IOS,

```
FCM.presentLocalNotification({
				id: 'clipboard',
				body: 'Copied ' + value + ' to clipboard',
				sound: 'default',
				priority: 'high',
				show_in_foreground: true,
			})
			FCM.removeDeliveredNotification("clipboard")
```

Is there any way to clear local notification from tray?
![glass](https://cloud.githubusercontent.com/assets/7381482/21994512/bc439d98-dc28-11e6-9130-0dbfdbb62609.png)

**Comment by evollu** [comment]
removeDeliveredNotifications

**Comment by evollu** [comment]
fixed with 4.0.3

**Comment by JaxGit** [comment]
Unfortunately native function removeDeliveredNotificationsWithIdentifiers only accepts uuid instead of gcm.message_id. 

I guess [[UNUserNotificationCenter currentNotificationCenter] getDeliveredNotificationsWithCompletionHandler:<#^(NSArray<UNNotification *> * _Nonnull notifications)completionHandler#>]
should be used whenever receiving a new notification to retrieve all with uuid identifiers to determine which ones to remove.

**Comment by evollu** [comment]
You can set id when you create local notification

**Comment by JaxGit** [comment]
Thanks you are right about tracking local notifications. I was thinking another scenario in #306

**Comment by evollu** [comment]
closing this. feel free to reopen if you think necessary
