### ISSUE TITLE
Notification undefined within App

### ISSUE THREAD

**Issue by mitchmyburgh** [evollu/react-native-fcm#294]
When intergrating this library within a react-native application running on Android the following:
```
this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
   alert(notif);
});
```
shows that the notification is undefined. The notification appears when the app is closed, but is undefined when the app is open.

Running:
react-native v0.40.0
react-native-fcm 6.0.1
Android Device running Android 6.0.1

Kind Regards
Mitch

**Comment by Kottidev** [comment]
I have same problem

**Comment by evollu** [comment]
fixed in 6.0.2

**Comment by niranjan-b-prajapati** [comment]
@evollu when i earlier installed v2.5.6 i started getting **Notification undefined within App**  error, So as you mentioned that issue is fixed in 6.0.2 so i updated to 6.0.2.

But now i am getting **"React/RCTBridgeModule.h" not found** error 

so as per your solution in https://github.com/evollu/react-native-fcm/issues/272

the version to be installed is v2.5.6 as following are my react version in app :
"react": "15.3.1",
"react-native": "0.34.1",

Can you please suggest what to do.

**Comment by evollu** [comment]
@niranjan-b-prajapati 
for v2.5.6 you should use the old way (which is `"notification"`)
v6 depends on react-native v0.40+

**Comment by niranjan-b-prajapati** [comment]
@evollu can you please provide me with sample code of old way as i was following readme file.

**Comment by evollu** [comment]
@niranjan-b-prajapati  https://github.com/evollu/react-native-fcm/tree/v5.0.0

**Comment by niranjan-b-prajapati** [comment]
@evollu some small questions please, Any method that can be used to show notification as alert when app is open. & also what should be the notification icon name & icon size in android as i am only able to see white square box in notification. Need to take notification icon from app.

**Comment by evollu** [comment]
assume you are on android
check readme or example project in https://github.com/evollu/react-native-fcm/tree/v5.0.0
1. use white icon with transparent background for notification icons. android system requirement
2. for foreground push notification to show as banner, use `custom_notification`. check readme

**Comment by niranjan-b-prajapati** [comment]
@evollu I am building app for both android and ios and i am looking for some method which would be called when the app is in foreground so that the notification message received can be shown in alert. for example pushwoosh has a handler function which gets called when application is in foreground so the notification can be shown in alert.

I have added icon with transparent background, but still not showing. Is there any naming convention to be followed as my app icon in drawable folder is having different name.

**Comment by evollu** [comment]
for icon: you need to pass `icon` in payload
for foreground: if you pass `data` in fcm payload, the callback will be called even when app is in foreground. If you want to show system notification banner, call presentLocalNotification in the callback with `show_in_foreground: true`.
