### ISSUE TITLE
How to detect notification open when app running background?

### ISSUE THREAD

**Issue by umhan35** [evollu/react-native-fcm#32]
I implemented the notification handling for the states of foreground-running and not-running. But when the app is in background and users click on the notification, how does the app detect that and run the same code as the not-running case?

Thanks

**Comment by evollu** [comment]
I'm a little confused. Are you trying to differentiate background vs foreground or background vs not running?

**Comment by evollu** [comment]
Which platform are you using?

**Comment by umhan35** [comment]
iOS.

Sorry for the delay, but I'll rephrase my question:

I implemented the notification handling for the states of foreground-running (the notification event `FCM.on('notification', ...)`, an alert) and not-running (just set `FCM.initialData` a state and check, directly open a webview to see the notification content). But when the app is in background and users click on the notification, the alert still shown while I want the app to directly open a webview to see the notification content. Is there a way to check if user just tapped the notification and the app is brought to foreground?

Thanks

**Comment by evollu** [comment]
If I understand you correctly, you are trying to pass the same notification and want the app to behave differently based on current status?

**Comment by evollu** [comment]
for ios:
set `content_available` to be true, so that you will get the notif twice, once in background, once on resume. in react native code, check if app is in background or not. If in background, just open webview directly.
for android
if you pass `notification` payload only, app running in foreground should not receive anything but app in background will receive something on resume.

**Comment by umhan35** [comment]
It works! thanks
