### ISSUE TITLE
Override module error

### ISSUE THREAD

**Issue by pablood85** [evollu/react-native-fcm#33]
Hello!

I followed the instructions for Android installation, but once I open the app I receive this error: https://s31.postimg.org/kbkt4sby3/2016_07_04_10_40_11.png

Any help is appreciated.

**Comment by pablood85** [comment]
Well, it looks like it works if you just add this method to FIRMessagingModule.java

```
    public boolean canOverrideExistingModule(){
        return true;
    }
```
Do you think it is related to the Android version? I tested it in K (4.4.2)

**Comment by yuenanto** [comment]
Your problem is the same as #29
Make sure you only have **once** the `new FIRMessagingPackage()` in the `MainActivity.java`.

It usually happens when you have already set manually the config and then do a ```rnpm install react-native-fcm```a second time.
The wrong way -->
![image](https://cloud.githubusercontent.com/assets/9156092/16589842/3c6bf7ce-42d5-11e6-9477-001e7d8b4cff.png)

**Comment by pablood85** [comment]
Thank you @yuenanto.
Let's close this issue.

**Comment by evollu** [comment]
@yuenanto thanks
