### ISSUE TITLE
Android App crashes when receiving notification from Firebase Notifications, iOS works fine.

### ISSUE THREAD

**Issue by douglaswissett** [evollu/react-native-fcm#358]
RN 0.42 fcm 6.1.0
Android 6 genymotion emulator

Android App crashes when receiving remote notification sent from firebase console. local notifications work fine on both platforms.

Remote notifications also work fine on iOS.

**Comment by RalfNieuwenhuizen** [comment]
You should add 

    ```compile 'com.google.firebase:firebase-messaging:10.0.1'```

to your `android/app/build.gradle` config

**Comment by GrishmaM** [comment]
im facing the same issue 
is it resolved for u ?

**Comment by Dror-Bar** [comment]
Of course I have added that line Ralf suggested (by thoroughly following the guides), but whenever I try to send notification through Firebase's Notifications composer the app crashes. Any idea why?

**Comment by jolinkomo-code** [comment]
same problem

**Comment by Dror-Bar** [comment]
I should say that I managed to solve my problem eventually.

I don't know if this will help anyone else, but it might. What I had to do was open the project in Android Studio. Then I repeat the steps, and most importantly, sync the gradle. After that it started working properly instead of crashing the app.
