### ISSUE TITLE
opened_from_tray is 1 when opening app by tapping the app icon

### ISSUE THREAD

**Issue by ExplodingCabbage** [evollu/react-native-fcm#363]
When I open my app by tapping the app icon (with no notifications involved at all) and call `FCM.getInitialNotification()`, I get an object with `opened_from_tray` set to 1. This seems incorrect since, per the README, `opened_from_tray` being truthy is meant to indicate that the app was opened via tapping a banner notification (I think).

> What version of RN and react-native-fcm are you running?

RN 0.42.0, react-native-fcm 6.1.0

> What device are you using? (e.g iOS9 emulator, Android 6 device)?

Android emulator.

**Comment by jordanmkoncz** [comment]
I'm getting the same behaviour, but it only seems to be happening on Android for me.

I'm running in the Android emulator using Android 6.0, and using the following dependencies:

```
"react": "~15.4.0",
"react-native": "0.41.2",
"react-native-fcm": "^6.1.0",
```

**Comment by coreform** [comment]
I see the same.

from console.log of the notification:
```
Object {opened_from_tray: 1, fcm: Object}
fcm
: Object
action: null
```

```
"react": "16.0.0-alpha.6",
"react-native": "0.43.4",
"react-native-fcm": "^6.2.3",
```

**Comment by cooperka** [comment]
Same issue on latest `react-native-fcm v7.0.3`, Android 7.0 physical device. I noticed the payload is very different in each case.

### Example

For the following FCM payload:

```js
{
  notification: {
    body: 'body',
    title: 'title',
  }
}
```

(1) Event received while the app is active:

```js
{
  fcm: {
    body: 'body',
    title: 'title',
    /* ... */
  },
  finish: function,
  collapse_key: 'com.myapp',
  from: '...',
  'google.message_id': '...',
  'google.sent_time': 1498238344823,
}
```

(2) No event received while the app is inactive.

(3) Event received after tapping the notification:

```js
{
  fcm: {
    // This is the ONLY thing here (no body or title).
    action: 'android.intent.action.MAIN',
  },
  finish: function,
  collapse_key: 'com.myapp',
  from: '...',
  'google.message_id': '...',
  'google.sent_time': 1498238344823,
  opened_from_tray: 1,
}
```

(4) Event received after minimizing the app and then opening it again via the app icon:

```js
{
  fcm: {
    // This is the ONLY thing here (no body or title).
    action: 'android.intent.action.MAIN',
  },
  finish: function,
  profile: 0,
  opened_from_tray: 1,
}
```

### Workaround

Check if `google.sent_time` exists. If so, assume the notification is valid (and trust the value of `opened_from_tray`). Otherwise, ignore the event entirely.

I hope this helps!

**Comment by cooperka** [comment]
### Update (better fix)

This seems to be solved by sending an explicit `click_action` (see [README example](https://github.com/evollu/react-native-fcm#behaviour-when-sending-notification-and-data-payload-through-gcm)). Then the `fcm` data always contains e.g. `action: 'fcm.ACTION.HELLO'` and **I no longer get any event when opening the app via the app icon**.

Also make sure you've [registered for the action](https://github.com/evollu/react-native-fcm#config-for-notification-and-click_action-in-android) in your `AndroidManifest.xml`, otherwise your app won't open when you tap the notification.

This is still a weird bug, but when sending a `click_action` properly, it's completely avoided.

**Comment by connercms** [comment]
@cooperka where do you define the click_action? Can you paste an example of your push notification code. I am having the hardest time understanding this documentation

**Comment by cooperka** [comment]
@connercms see the example in the README. You send `click_action` as part of your FCM payload (the data you POST to FCM). The app will receive this and `react-native-fcm` will handle it for you.

FCM payload:

```json
{
   "to":"some_device_token",
   "content_available": true,
   "notification": {
       "title": "hello",
       "body": "yo",
       "click_action": "fcm.ACTION.HELLO"
   },
   "data": {
       "extra":"juice"
   }
}
```

Received by your app after being handled by `react-native-fcm` (in your `FCM.on(FCMEvent.Notification, (notification) => { /* HERE */ })` callback):

```json
{
  "fcm": {"action": "fcm.ACTION.HELLO"},
  "opened_from_tray": 1,
  "extra": "juice"
}
```

(this is just a direct copy from the README)

**Comment by connercms** [comment]
@cooperka But like the OP said, there is no notification involved, so where do you specify the click_action? Simply opening the app from pressing the icon from the home screen triggers FCM.on(FCMEvent.Notification..) and notif.opened_from_tray is true when there are no notifications. Or is this a separate issue?

**Comment by cooperka** [comment]
Ah, I see what you mean. In my case at least, there **was** a notification originally, which caused this library to start acting up. If you send a new notification with `click_action`, it should stop triggering incorrectly when you open your app.

**Comment by yjb94** [comment]
since this bug hasn't been fixed, I've just compared the payload for android

**Comment by luisfuertes** [comment]
I add click_action on my notif controller in server side, at same level that body and title, because i cant get my notif data when i click in notif whit app in background.

But now my app dont open when i click on notif in backgraund. I have to declare the click_action in manifest or in FCM component?

**Comment by quintonn** [comment]
does this issue have a solution yet?
I am sending click_action, but one of my clients are experiencing this on their android phone

**Comment by evollu** [comment]
This behavior is expected. You will receive opened_from_tray all the time in initial notification in Android. But you can filter out the app icon launch by looking at intent property.
If Notif.action === "android.intent.action.MAIN" then ignore the notification

**Comment by jordanmkoncz** [comment]
Thanks for commenting @evollu. Are you sure this issue should be closed though? This seems like a bug to me. The docs essentially state that `opened_from_tray` is `true` when "app is open/resumed because user clicked banner". But the actual behaviour we're seeing is that `opened_from_tray` is `true` even when the app is just opened normally by clicking on the app icon from the home screen / launcher, which is the opposite of what the docs state. The fact that `opened_from_tray` behaves correctly (i.e. according to what the docs state) on iOS but behaves completely differently on Android also seems to imply this is a bug, since there's no reason to think that `opened_from_tray` would mean something different on Android versus iOS.

If this is somehow not a bug and is working exactly as intended, then I think the docs should be updated to explain the actual behaviour of `opened_from_tray` because currently they are misleading/incorrect, at least for Android.

**Comment by ExplodingCabbage** [comment]
Indeed; this part of the documentation is just plain false:

```
    if(notif.opened_from_tray){
      //app is open/resumed because user clicked banner
    }
```

It's unhelpful and unintuitive for the behaviour to differ between iOS and Android in the first place, but *if* that can't be helped, the behaviour at least shouldn't be documented falsely.

**Comment by evollu** [comment]
This is something can't be fixed thanks to Samsung's special behavior.
will update readme.

**Comment by pkhien95** [comment]
@cooperka I still cannot understand why there is no `title` and `body` in `fcm` object when notification is tapped on tray (app was on background or killed). How can I get `title` and `body` in this case?

**Comment by ferdinandosp** [comment]
I get the exact same issue like @pkhien95 explained.
The title and body of the notification shows up when the app is opened. Why it doesn't when the app is in background?

**Comment by sairohithA007** [comment]
Even I'm having the same issue as @ferdinandosp and @pkhien95. But in my case, when I tap on notification the app is not coming into foreground automatically but when I manually open the app, I'm automatically navigated to the screen which I mentioned on notification open from tray.
