### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by ashah888** [evollu/react-native-fcm#404]
Using the latest React Native 0.44.0 and react-native-fcm 6.2.3,

Building the app fails with "Apple Mach-O Linker Error".

Followed all the proper steps of Podfile, react-native link, and GoogleService-info.plist.

Please help.

**Comment by nmhcoc** [comment]
@ashah888  try open yourProject.xcworkspace and build

**Comment by didaKtik** [comment]
@ashah888 Have you found a solution? I have the same issue.

**Comment by sarath263** [comment]
Have anyone tried without Cocoapods?

**Comment by didaKtik** [comment]
Yes we tried and got the same error

**Comment by dfischer** [comment]
@nmhcoc your solution worked, thanks

**Comment by evollu** [comment]
please reopen the issue if you have more question

**Comment by kaiserama** [comment]
Not sure if this is causing problems for anyone else, but after a few hours of trying things all over the web what finally worked for me was that I just needed to add `$(inherited)` to my Build Settings/ Framework Search Path.  That fixed everything for me.  Hope it helps someone else!

**Comment by satishmane** [comment]
Hi,
I am able to build successfully using workspace. But I ran into another problem. My testfairy fails now during build when I do using workspace. In short, if I build using pbxproject, then it fails with linker error and no testfairy linking error. but if I build using workspace, then it fcm linker error goes away, but I get testfairy link error.

is there way to solve fcm linker error using pbxproject instead of using cocoapods
