### ISSUE TITLE
How to get new instance id after deleting this previous one.

### ISSUE THREAD

**Issue by imbudhiraja** [evollu/react-native-fcm#539]
FCM.deleteInstanceId()
            .then( () => {
              //Deleted instance id successfully
              //This will reset Instance ID and revokes all tokens.
            })
            .catch(error => {
              //Error while deleting instance id
            });

**Comment by SpidGiarz** [comment]
This will notify of token refresh

`FCM.on(FCMEvent.RefreshToken, (token) => { ... });`

**Comment by imbudhiraja** [comment]
@SpidGiarz thanks i got this earlier.

**Comment by konradkierus** [comment]
@imbudhiraja  @SpidGiarz did you manage to get a new token for iOS after calling the deleteInstanceId method when using this lib?

**Comment by konradkierus** [comment]
I will answer myself to the above question and leave the answer here for future readers.

Make sure you have the newest Firebase SDK (for example do 'pod update') then everything is working as expected. 

I was surprised that their documentation says that request for new token is automatically called right after calling the deleteInstanceId so I've tracked the problem was with my outdated pods (https://firebase.google.com/docs/reference/ios/firebaseinstanceid/api/reference/Classes/FIRInstanceID#/c:objc(cs)FIRInstanceID(im)deleteIDWithHandler:)
