### ISSUE TITLE
Remote notifications event not triggered in Android

### ISSUE THREAD

**Issue by xavieramoros** [evollu/react-native-fcm#583]
RN: 0.48.4
react-native-fcm: 9.6.2
Android 6.0.1
Devices: Samsung J5, One Plus 2

@evollu in Android I can receive local and remote notifications both in foreground/background/killed. My problem is that while the app is in background/killed, I don't get any **event** for remote notifications (the notification is shown correctly). The event is not triggered even when clicking on the notification. 

I'm sending the remote notifications with Firebase Console.

Things I tried:
-use FCM.getInitialNotification() as suggested in #558. 
-Use AppState to detect when the app comes from background to getInitialNotifiaction
-FCM.on(FCMEvent.Notification...) is placed outside of the component code
-Adding in MainActivity.java (as suggested in #341):
```
@Override
public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    this.setIntent(intent);
}
```

I also found this thread in Stack Overflow: https://stackoverflow.com/a/37845174, that says it's not possible to send Data Messages from Firebase Console. Is that the case? I'm pretty sure with older versions of react-native-fcm (6.2.3) I was receiving the event correctly (app in background and remote notification).

**Comment by evollu** [comment]
it needs to be data only notification to trigger the callback I think.

**Comment by chrusart** [comment]
Look at #588

**Comment by wwwdata** [comment]
Also had this problem and was trying around forever with the firebase console ... as it turns out, notifications that have a `notification` body and would display a notification text and so on, are indeed not handled in the background. Notifications/Messages that only have a data part will be handled in the background and when the app is closed as soon as the app starts again. But they will then not show up in the android notification center... 

Works in Background:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: key=theKey" -d '{ "data": { "someData": "test123" }, "to": "deviceID" }' https://fcm.googleapis.com/fcm/send
```

Does not work in Background:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: key=theKey" -d '{ "data": { "navPath": "test123" }, "to": "clientID", "notification": {  "body": "hey"  }}' https://fcm.googleapis.com/fcm/send
```

This is confusing me, why can we not have both like on iOS? I want to receive a notification with a text and when the user presses it, navigate to the according screen in my app. How would I manage to do that?

**Comment by nhuthan** [comment]
my problem is getInitialNotification alway return null (not undefined) when i press notification on tray.

**Comment by evollu** [comment]
FCM ignores `data` if it is send together with `notification`. can't do anything about it

**Comment by wwwdata** [comment]
@evollu so how can I send a notification and when the user taps on it open a specific page inside my app? Is this not possible with fcm notifications?

**Comment by evollu** [comment]
it is. you have to use "custom_notification" to ensure delivery

**Comment by wwwdata** [comment]
@evollu thank you so much, that works 👍  Totally overlooked that in the Readme
